SUMMARY = "Container signing, verification and storage in an OCI registry"
HOMEPAGE = "https://github.com/sigstore/cosign"
LICENSE = "Apache-2.0 AND BSD-2-Clause AND MIT AND MPL-2.0"
LIC_FILES_CHKSUM = "file://${S}/src/${GO_IMPORT}/COPYRIGHT.txt;md5=3830a9ca4f9dc30be01bfa2e4042dd46 \
                    file://${S}/src/${GO_IMPORT}/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327 \
                    "

GO_IMPORT = "github.com/sigstore/cosign"

SRC_URI = "git://github.com/sigstore/cosign.git;branch=main;name=cosign;protocol=https;destsuffix=${GO_SRCURI_DESTSUFFIX}"
PV = "3.1.3+git"
SRCREV_cosign = "e9a91ea113bfc8102a4385c4ac477285e4b74cee"

SRCREV_FORMAT = "cosign"

# go-mod-discovery configuration
GO_MOD_DISCOVERY_SRCDIR = "${S}/src/${GO_IMPORT}"
GO_MOD_DISCOVERY_BUILD_TARGET = "./cmd/cosign"
GO_MOD_DISCOVERY_LICENSE_TARGETS = "./cmd/cosign"
GO_MOD_DISCOVERY_GIT_REPO = "https://github.com/sigstore/cosign.git"
GO_MOD_DISCOVERY_GIT_REF = "${SRCREV_cosign}"

# Modules that can't be fetched via git (no repo metadata or unreachable commits)
# - buf.build/gen/go: generated protobuf module, no git repository
# - github.com/open-policy-agent/opa: pinned commit not reachable via shallow fetch
SRC_URI += "gomod://buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go;version=v1.36.11-20260709200747-435963d16310.1;sha256sum=${COSIGN_BUF_BUILD_SHA}"
SRC_URI += "gomod://github.com/open-policy-agent/opa;version=v1.20.2;sha256sum=${COSIGN_OPA_SHA}"
GO_MOD_VCS_EXCLUDE = "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go github.com/open-policy-agent/opa"

# Checksums — run bitbake cosign -c fetch to get correct values on first use
COSIGN_BUF_BUILD_SHA ?= "7d3f740646193cc6f3b191223817fad3d0fe636b203163b4425da90bfb47a99e"
COSIGN_OPA_SHA ?= "d8cb5f5a1a59bffa3d473b21800f6a25d62999c301fe86c884b756c187ecee10"

# GO_MOD_FETCH_MODE: "vcs" (all git://) or "hybrid" (gomod:// + git://)
GO_MOD_FETCH_MODE ?= "hybrid"

# VCS mode: all modules via git://
include ${@ "go-mod-git.inc" if d.getVar("GO_MOD_FETCH_MODE") == "vcs" else ""}
include ${@ "go-mod-cache.inc" if d.getVar("GO_MOD_FETCH_MODE") == "vcs" else ""}

# Hybrid mode: gomod:// for most, git:// for selected
include ${@ "go-mod-hybrid-gomod.inc" if d.getVar("GO_MOD_FETCH_MODE") == "hybrid" else ""}
include ${@ "go-mod-hybrid-git.inc" if d.getVar("GO_MOD_FETCH_MODE") == "hybrid" else ""}
include ${@ "go-mod-hybrid-cache.inc" if d.getVar("GO_MOD_FETCH_MODE") == "hybrid" else ""}

# Dependency license tracking (generated by oe-go-mod-fetcher --scan-licenses)
require go-mod-licenses.inc

inherit go goarch
inherit go-mod-discovery

BBCLASSEXTEND = "native nativesdk"
